export const SliderData = [
  {
    image:
      'https://images.unsplash.com/photo-1546768292-fb12f6c92568?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni officiis dicta minima nobis nisi harum architecto sint neque est rerum quod dolorum voluptas non molestias recusandae eos, atque, vitae dolore, saepe optio distinctio aut officia. Aliquid est optio dolore, porro fugit molestias praesentium atque ipsam enim placeat nisi, reiciendis magni consectetur. Praesentium, placeat laborum! Velit cum vero, incidunt cupiditate reiciendis soluta vel iste quod nihil omnis dicta beatae enim quae quis porro saepe iure odit est dolor laborum nesciunt! Distinctio necessitatibus quisquam est veniam dicta debitis ipsam, magnam modi repellendus reprehenderit aut! Numquam alias error ducimus eius! Doloremque, inventore et pariatur quod illum impedit exercitationem nostrum modi eveniet, reiciendis sint perspiciatis officia nemo vitae nulla numquam natus sit odio eius fuga. Reprehenderit necessitatibus tempora quaerat officiis saepe libero. Ut, totam! Illo voluptatem, provident corrupti laboriosam aliquam voluptatum! Labore odio soluta explicabo, velit nulla enim? Ea error, modi quibusdam tempore repellendus est nulla laudantium, cumque impedit facilis similique dolorum dignissimos debitis suscipit. Magnam necessitatibus dignissimos aliquam laboriosam ipsum a debitis temporibus laudantium?",
    position : "left"
  },
  {
    image:
      'https://images.unsplash.com/photo-1501446529957-6226bd447c46?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1489&q=80',
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni officiis dicta minima nobis nisi harum architecto sint neque est rerum quod dolorum voluptas non molestias recusandae eos, atque, vitae dolore, saepe optio distinctio aut officia. Aliquid est optio dolore, porro fugit molestias praesentium atque ipsam enim placeat nisi, reiciendis magni consectetur. Praesentium, placeat laborum! Velit cum vero, incidunt cupiditate reiciendis soluta vel iste quod nihil omnis dicta beatae enim quae quis porro saepe iure odit est dolor laborum nesciunt! Distinctio necessitatibus quisquam est veniam dicta debitis ipsam, magnam modi repellendus reprehenderit aut! Numquam alias error ducimus eius! Doloremque, inventore et pariatur quod illum impedit exercitationem nostrum modi eveniet, reiciendis sint perspiciatis officia nemo vitae nulla numquam natus sit odio eius fuga. Reprehenderit necessitatibus tempora quaerat officiis saepe libero. Ut, totam! Illo voluptatem, provident corrupti laboriosam aliquam voluptatum! Labore odio soluta explicabo, velit nulla enim? Ea error, modi quibusdam tempore repellendus est nulla laudantium, cumque impedit facilis similique dolorum dignissimos debitis suscipit. Magnam necessitatibus dignissimos aliquam laboriosam ipsum a debitis temporibus laudantium?",
    position : "right"
  },
  {
    image:
      'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80',
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni officiis dicta minima nobis nisi harum architecto sint neque est rerum quod dolorum voluptas non molestias recusandae eos, atque, vitae dolore, saepe optio distinctio aut officia. Aliquid est optio dolore, porro fugit molestias praesentium atque ipsam enim placeat nisi, reiciendis magni consectetur. Praesentium, placeat laborum! Velit cum vero, incidunt cupiditate reiciendis soluta vel iste quod nihil omnis dicta beatae enim quae quis porro saepe iure odit est dolor laborum nesciunt! Distinctio necessitatibus quisquam est veniam dicta debitis ipsam, magnam modi repellendus reprehenderit aut! Numquam alias error ducimus eius! Doloremque, inventore et pariatur quod illum impedit exercitationem nostrum modi eveniet, reiciendis sint perspiciatis officia nemo vitae nulla numquam natus sit odio eius fuga. Reprehenderit necessitatibus tempora quaerat officiis saepe libero. Ut, totam! Illo voluptatem, provident corrupti laboriosam aliquam voluptatum! Labore odio soluta explicabo, velit nulla enim? Ea error, modi quibusdam tempore repellendus est nulla laudantium, cumque impedit facilis similique dolorum dignissimos debitis suscipit. Magnam necessitatibus dignissimos aliquam laboriosam ipsum a debitis temporibus laudantium?",
    position : "left"
  },
  {
    image:
      'https://images.unsplash.com/photo-1475189778702-5ec9941484ae?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1351&q=80',
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni officiis dicta minima nobis nisi harum architecto sint neque est rerum quod dolorum voluptas non molestias recusandae eos, atque, vitae dolore, saepe optio distinctio aut officia. Aliquid est optio dolore, porro fugit molestias praesentium atque ipsam enim placeat nisi, reiciendis magni consectetur. Praesentium, placeat laborum! Velit cum vero, incidunt cupiditate reiciendis soluta vel iste quod nihil omnis dicta beatae enim quae quis porro saepe iure odit est dolor laborum nesciunt! Distinctio necessitatibus quisquam est veniam dicta debitis ipsam, magnam modi repellendus reprehenderit aut! Numquam alias error ducimus eius! Doloremque, inventore et pariatur quod illum impedit exercitationem nostrum modi eveniet, reiciendis sint perspiciatis officia nemo vitae nulla numquam natus sit odio eius fuga. Reprehenderit necessitatibus tempora quaerat officiis saepe libero. Ut, totam! Illo voluptatem, provident corrupti laboriosam aliquam voluptatum! Labore odio soluta explicabo, velit nulla enim? Ea error, modi quibusdam tempore repellendus est nulla laudantium, cumque impedit facilis similique dolorum dignissimos debitis suscipit. Magnam necessitatibus dignissimos aliquam laboriosam ipsum a debitis temporibus laudantium?",
    position : "right"
  },
  {
    image:
      'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1350&q=80',
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni officiis dicta minima nobis nisi harum architecto sint neque est rerum quod dolorum voluptas non molestias recusandae eos, atque, vitae dolore, saepe optio distinctio aut officia. Aliquid est optio dolore, porro fugit molestias praesentium atque ipsam enim placeat nisi, reiciendis magni consectetur. Praesentium, placeat laborum! Velit cum vero, incidunt cupiditate reiciendis soluta vel iste quod nihil omnis dicta beatae enim quae quis porro saepe iure odit est dolor laborum nesciunt! Distinctio necessitatibus quisquam est veniam dicta debitis ipsam, magnam modi repellendus reprehenderit aut! Numquam alias error ducimus eius! Doloremque, inventore et pariatur quod illum impedit exercitationem nostrum modi eveniet, reiciendis sint perspiciatis officia nemo vitae nulla numquam natus sit odio eius fuga. Reprehenderit necessitatibus tempora quaerat officiis saepe libero. Ut, totam! Illo voluptatem, provident corrupti laboriosam aliquam voluptatum! Labore odio soluta explicabo, velit nulla enim? Ea error, modi quibusdam tempore repellendus est nulla laudantium, cumque impedit facilis similique dolorum dignissimos debitis suscipit. Magnam necessitatibus dignissimos aliquam laboriosam ipsum a debitis temporibus laudantium?",
    position : "left"
  },
  {
    image:
      'https://images.unsplash.com/photo-1659482633347-e56ce63d147b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDF8MHxlZGl0b3JpYWwtZmVlZHw0MHx8fGVufDB8fHx8&auto=format&fit=crop&w=500&q=60',
    text: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Magni officiis dicta minima nobis nisi harum architecto sint neque est rerum quod dolorum voluptas non molestias recusandae eos, atque, vitae dolore, saepe optio distinctio aut officia. Aliquid est optio dolore, porro fugit molestias praesentium atque ipsam enim placeat nisi, reiciendis magni consectetur. Praesentium, placeat laborum! Velit cum vero, incidunt cupiditate reiciendis soluta vel iste quod nihil omnis dicta beatae enim quae quis porro saepe iure odit est dolor laborum nesciunt! Distinctio necessitatibus quisquam est veniam dicta debitis ipsam, magnam modi repellendus reprehenderit aut! Numquam alias error ducimus eius! Doloremque, inventore et pariatur quod illum impedit exercitationem nostrum modi eveniet, reiciendis sint perspiciatis officia nemo vitae nulla numquam natus sit odio eius fuga. Reprehenderit necessitatibus tempora quaerat officiis saepe libero. Ut, totam! Illo voluptatem, provident corrupti laboriosam aliquam voluptatum! Labore odio soluta explicabo, velit nulla enim? Ea error, modi quibusdam tempore repellendus est nulla laudantium, cumque impedit facilis similique dolorum dignissimos debitis suscipit. Magnam necessitatibus dignissimos aliquam laboriosam ipsum a debitis temporibus laudantium?",
    position : "right"
  },
  
];
